### ISSUE TITLE
Duplicate rules when using with postcss-modules

### ISSUE THREAD

**Issue by niksajanjic** [csstools/postcss-preset-env#114]
This is a very minor issue as it doesn't break anything, it just generates duplicate rules in case of using custom properties with `postcss-modules`.

Let's say we have this input CSS file (using SugarSS syntax):
```sss
:root
  --background: #000

.test
  background: var(--background)
  color: #fff
```

And our __.postcssrc.js__ looks like this:
```js
module.exports = {
  parser: 'sugarss',
  plugins: {
    'postcss-preset-env': {},
    'postcss-modules': {},
  },
}
```

Resulting CSS file will have duplicate rules:
```css
:root {
  --background: #000
}

._test_js365_4 {
  background: #000;
  background: #000;
  background: var(--background);
  color: black
}
```

As you can see, it duplicated `background: #000` rule for some reason. If I remove `postcss-modules` from PostCSS configuration duplication will not happen of course. I don't know why is that happening and as far as I could tell it can be a `postcss-modules` plugin fault.

In case of production build, I'm using `cssnano` so I don't have any duplicated rules, nor does this prevent me from developing, it's just a bit irritating to see a bunch of duplicated rules in case your class uses a lot of custom variables.
