### ISSUE TITLE
Custom media queries don't seem to work

### ISSUE THREAD

**Issue by afk-mcz** [csstools/postcss-preset-env#119]
I'm using postcss-preset-env with gatsbyjs and my custom queries don't seem to work, I tried a lot of different and can't get it working. Is there anything I'm missing?

```json
    "postcss-preset-env": "^6.6.0",
    "gatsby-plugin-postcss": "^2.0.7",
```

My postcss.config.js

```js
module.exports = () => ({
  plugins: {
    'postcss-import': {},
    'postcss-preset-env': {
      features: {
        customProperties: {
          warnings: false,
        },
      },
    },
    'postcss-custom-media': {
      importFrom: 'src/styles/queries.css',
    },
  },
});
```

My queries.css
```css
@custom-media --small-screen (width <= 670px);
@custom-media --medium-screen (width <= 1000px);
@custom-media --big-screen (width < 1200px);
@custom-media --not-small-screen (width > 670px);
```

Example css using custom media queries

```css
@media (--small-screen) {
  .hide-mobile {
    display: none;
  }

  .wrapper {
    width: 90%;
  }
}
```
