### ISSUE TITLE
nesting-rules does not work

### ISSUE THREAD

**Issue by a-x-** [csstools/postcss-preset-env#127]
`stage: 1` or `features: { 'nesting-rules': true' }`
does not help

I tried webpack and postcss-cli setups

I use latest versions of everything:
- "postcss": "^7.0.16",
- "postcss-preset-env": "^6.6.0"
- "postcss-cli": "^6.1.2",

**conf** postcss.config.js:
```js
const postcssEnv = require('postcss-preset-env');

module.exports = {
        plugins: [
                postcssEnv({
                        browsers: ['last 1 Chrome version'],
                        features: {
                                'nesting-rules': true,
                        }
                }),
        ]
}
```

**input** src/index.css:
```css
.root {
	body .root {
		color: red;
	}
}
```

**output** dist/index.css:
```css
._4PyOEkPRV4QzG83E2F0tA {
        body ._4PyOEkPRV4QzG83E2F0tA {
                color: red;
        }
}
```
