### ISSUE TITLE
Confused about importFrom and the expected output

### ISSUE THREAD

**Issue by morganfeeney** [csstools/postcss-preset-env#141]
Hi Jonathan, I'm trying to work out what I should expect the output CSS to look like once it has received some more CSS via `importFrom`, and been processed. 
I created a reduced test case which you can see [here](https://github.com/morganfeeney/postcss-preset-env-grunt-test).

This is what I am expecting when I use `importFrom`: I import the contents of [this](https://github.com/morganfeeney/postcss-preset-env-grunt-test/blob/master/src/css/test.css) file with some custom properties assigned to `:root`, e.g.:

```css
:root {
  --test: green;
}
```

When I reference the imported custom properties like I do in [this](https://github.com/morganfeeney/postcss-preset-env-grunt-test/blob/master/src/scss/typography.scss) file, e.g.

```scss
h2 {
  color: var(--test);
}
```

I expect the resulting CSS to also include the rules that assign the custom properties to `:root`, e.g.

```css
:root {
  --test: green;
}

h2 {
  color: green;
  color: var(--test);
}
```

...but that doesn't happen, I do however get the transpiled value of `green`, which you can see in [this](https://github.com/morganfeeney/postcss-preset-env-grunt-test/blob/master/dest/css/style.css) file, and the preserved custom property, which seems useless (unless the values are supposed to be passed in to other custom properties?) because its value has not been set, e.g.

```css
h2 {
  color: green;
  color: var(--test);
}
```

So... is this expected, if not, what am I doing wrong?
