### ISSUE TITLE
Adding :is

### ISSUE THREAD

**Issue by equinusocio** [csstools/postcss-preset-env#155]
Does [`:is`](https://github.com/csstools/postcss-is-pseudo-class) plugin will be added to preset-env?

**Comment by jonathantneal** [comment]
@equinusocio, yes, but not until that plugin is able to do a few things correctly.

For example, the following rules are equivalent:

```css
:is(a, button):is(:hover, :focus) { order: 1; }
:is(:hover, :focus):is(a, button) { order: 2; }
```

They should both become something like this:

```css
a:hover, button:hover, a:focus, button:focus { order: 1; }
a:hover, button:hover, a:focus, button:focus { order: 2; }
```

But instead, currently, they become this:

```css
a:hover:focus, button:hover:focus { order: 1; }
a:hover, button:hover, a:focus, button:focus { order: 2; }
```

Until I can fix that bug, I do not want to integrate that plugin.
