### ISSUE TITLE
system-ui doesn't get replaced in custom properties

### ISSUE THREAD

**Issue by Hypnosphi** [csstools/postcss-preset-env#160]
Same as https://github.com/JLHwung/postcss-font-family-system-ui/issues/65

**Comment by romainmenke** [comment]
This works in latest version.

Input :

```css
test {
	font: italic bold 12px/30px system-ui, Helvetica Neue, sans-serif;
	font: italic bold 12px/30px system-ui, sans-serif;
	font: italic bold 12px/30px sans-serif;
	font-family: system-ui, Helvetica Neue, sans-serif;
	font-family: system-ui, sans-serif;
	font-family: system-ui;
	font-family: sans-serif;
	font-family: "Droid Sans", system-ui, sans-serif;
}

:root {
	--primary-font-family: system-ui, sans-serif;
	--首要的字体族: system-ui, sans-serif;
	\002d\002Di-am-a-custom-property: system-ui, sans-serif;
	-i-am-not-a-custom-property: system-ui, sans-serif;
}
```

Output :

```css
test {
	font: italic bold 12px/30px system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif, Helvetica Neue, sans-serif;
	font: italic bold 12px/30px system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;
	font: italic bold 12px/30px sans-serif;
	font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif, Helvetica Neue, sans-serif;
	font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;
	font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;
	font-family: sans-serif;
	font-family: "Droid Sans", system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;
}

:root {
	--primary-font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;
	--首要的字体族: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;
	\002d\002Di-am-a-custom-property: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;
	-i-am-not-a-custom-property: system-ui, sans-serif;
}

```
