### ISSUE TITLE
Not working on css imported from node_modules?

### ISSUE THREAD

**Issue by damianobarbati** [csstools/postcss-preset-env#166]
My `.postcssrc`:
```json
{
    "modules": true,
    "plugins": {
        "postcss-preset-env": {
            "stage": 1,
            "features": {
                "nesting-rules": true
            },
            "preserve": false,
            "importFrom": "node_modules/mymodule/src/css/imports/variables.css",
            "autoprefixer": true
        }
    }
}
```

My `app.css`:
```css
@import "@translated/common-web/src/css/main.css";

@media (--lg) {
    body {
        background-color: grey;
    }
}
```

I see the custom-media defined in `app.css` applied correctly applied correctly to the `body`.
But in `main.css` I have styles for h1 and h2 using the custom-media as well and they are not applied/transpiled.

Does anyone know how to solve this?
