### ISSUE TITLE
Preserve for specific CSS variables

### ISSUE THREAD

**Issue by dashkevych** [csstools/postcss-preset-env#168]
Hi,

I am wondering if it's possible to set `preserve` only for specific CSS variables, meaning to provide a fallback just for selected CSS variables.

For example, if we have the following CSS:

```css
:root {
  --main-font: "Helvetica";
  --main-color: blue;
}
```

So, instead of providing a fallback for both variables (`--main-font:`and `--main-color` ), just create a fall for `--main-color`.
