### ISSUE TITLE
`preserve` causes strange behavior with `gray()`

### ISSUE THREAD

**Issue by mikestopcontinues** [csstools/postcss-preset-env#173]
When `preserve: true`, I'm seeing this:

```css
body {
  color: gray(15);
  background-color: gray(100);
}
```

become:

```css
body {
  color: rgb(38,38,38);
  color: rgb(37,37,37);
  color: gray(15);
  background-color: rgb(255,255,255);
  background-color: rgb(255,255,254);
  background-color: gray(100);
}
```

I'm running the most recent version of everything, and I've tested this with all other plugins disabled. After the gray function, what's catching the rgb funcs?
