### ISSUE TITLE
Imported custom media not exported

### ISSUE THREAD

**Issue by sarahdayan** [csstools/postcss-preset-env#175]
Hi!

I'm importing custom properties and custom media queries using the documented JavaScript syntax. Problem is, only my custom properties are outputted, not the custom media queries.

Here's my `postcss.config.js` configuration:

```js
const postcssPresetEnv = require('postcss-preset-env');

module.exports = {
  plugins: [
    postcssPresetEnv({
      importFrom: {
        customProperties: {
          '--color-primary': '#d02139',
          '--color-secondary': '#21243d',
          '--text-fontFamily': "-apple-system, blinkmacsystemfont, 'Segoe UI', roboto, oxygen,\nubuntu, cantarell, 'Open Sans', 'Helvetica Neue', sans-serif"
        },
        customMedia: {
          '--breakpoint-sm-min': '(min-width: 640px)',
          '--breakpoint-sm-max': '(max-width: 640px)',
          '--breakpoint-md-min': '(min-width: 768px)',
          '--breakpoint-md-max': '(max-width: 768px)',
          '--breakpoint-lg-min': '(min-width: 1024px)',
          '--breakpoint-lg-max': '(max-width: 1024px)'
        }
      },
      exportTo: 'file.css'
    }),
  ],
};
```

And here are the contents of the generated `file.css` file:

```css
:root {
	--color-primary: #d02139;
	--color-secondary: #21243d;
	--text-fontFamily: -apple-system, blinkmacsystemfont, 'Segoe UI', roboto, oxygen,
ubuntu, cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
}
```

Additionally, the custom media queries aren't polyfilled in my built CSS file:

```css
@media (--breakpoint-sm-max) { ... }
```

## Things I've tried

1. I've tried with `customSelectors` and `environmentVariables` and they don't seem to work either, only `customProperties` do.
2. I've tried using [postcss/postcss-custom-media](https://github.com/postcss/postcss-custom-media) directly since it seemed like ` csstools/postcss-preset-env` uses it under the hood, and it does work. But I'd prefer using a single tool so I can have single exports.
3. I've tried with JSON and CSS files in `importFrom`, copy/pasting exactly the code from the docs, no luck here either.

Any idea what I might be doing wrong?
