### ISSUE TITLE
Autoprefixer (grid) transformations and custom properties don't mix well

### ISSUE THREAD

**Issue by lemonmade** [csstools/postcss-preset-env#180]
I have the following code:

```css
:root {
  --spacing: 10px;
}

.Test {
  gap: var(--spacing);
  grid-areas: 'leading trailing' auto / auto auto;
}
```

When transformed with `autoprefixer: {grid: true}`, this gets output as something like:

```css
/* omitting the original properties for brevity */
.Test {
  grid-gap: 10px;
  grid-gap: var(--spacing);
  -ms-grid-rows: auto;
  -ms-grid-columns: auto var(--spacing) auto;
}
```

The key bit is that the additional columns created to represent the gaps takes the original gap value, instead of the either taking the one that is guaranteed to work, or proving the same kind of progressive enhancement to the custom property if supported.
