### ISSUE TITLE
Invalid custom selector transformation

### ISSUE THREAD

**Issue by ar2r13** [csstools/postcss-preset-env#186]
```css
@custom-selector :--input input, ::slotted(input);

:--input:focus { ~ }
```

Expected: 
```css
input:focus, ::slotted(input:focus) { ~ }
```

Result:
```css
input:focus, ::slotted(input):focus { ~ }
```

**Comment by romainmenke** [comment]
In the latest version this still transform to :

```css
input:focus,::slotted(input):focus {
	order: 1;
}
```

This is technically correct I think as there is nothing in `@custom-selector :--input input, ::slotted(input);` indicating that it should insert something in `::slotted(...)` instead of after it.

I think nested css might be better fit for this.

```
:focus {
  @nest input&, ::slotted(input&) { ... }
}
```

-----------

Going to close this as this repo has moved and will be archived soon preventing further discussion here.

Feel free to open a new issue or discussion here : 
https://github.com/csstools/postcss-plugins
