### ISSUE TITLE
Error in calc()

### ISSUE THREAD

**Issue by fedorovsky** [csstools/postcss-preset-env#193]
This code throws a compilation error:

``` css
:root {
    --variable-top: 50px;
}

.some-class {
    margin-top: calc(-1 * var(--variable-top)); 
}
```
The problem is ```-1```. But my code above is valid.
But if I change -1 to -1px, it works
``` css
margin-top: calc(-1px * var(--variable-top)); 
````
![image](https://user-images.githubusercontent.com/7301838/95118720-72860d80-0753-11eb-8d65-a2174f1a1d2b.png)
