### ISSUE TITLE
css build error 

### ISSUE THREAD

**Issue by Summer-andy** [csstools/postcss-preset-env#194]
why not support  ?

```css
:root {
  --distance: 44px;
}

div {margin-top: calc(var(--distance)*-1/2);}
```
