### ISSUE TITLE
Logical properties stripped from CSS

### ISSUE THREAD

**Issue by smth** [csstools/postcss-preset-env#196]
With `logical-properties-and-values` enabled (as it is by default) logical properties are stripped from the returned CSS.

Reduced test case: https://codepen.io/smthdotuk/pen/RwGqZjY

With `logical-properties-and-values` set to `false` the property is present (along with a vendor prefix).

**Comment by gnehcwu** [comment]
Setting `logical-properties-and-values` to `false` should mean disable the processing for logical properties and output whatever original css is, (verder prefix mean autoprefixer is working?).
Came across this issue as well while using version(^6.7.0) at stage 0, suppose it should be replaced with non-logic values like `margin-left` or `margin-right` when enabled, but very strange, postcss just removed it directly, looks like the `stage 0` setting doesn't get respected at all...

**Comment by romainmenke** [comment]
@smth Thank you for your feedback.

The code pen is missing `dir` attribute and you are using `postcss-logical` without a `dir` plugin option.

Original HTML :

```html
<div class="my-class">
  Test
</div>
```

Input CSS :

```css
.my-class {
  border: solid 2px black;
  padding-inline-start: 1em;
}
```

----------

Better HTML :

```html
<div dir="ltr">
  <div class="my-class">
    Test
  </div>
</div>
```

Output CSS

```css
[dir="ltr"] .my-class {
  padding-left: 1em;
}
[dir="rtl"] .my-class {
  padding-right: 1em;
}
.my-class {
  border: solid 2px black;
}
```


------

You can either add a `dir="ltr|rtl"` attribute in your html or set a `dir` plugin option when transforming your CSS.
