### ISSUE TITLE
how to use custom properties set ?

### ISSUE THREAD

**Issue by 779102260** [csstools/postcss-preset-env#197]
like this

```css
:root {
  --danger-theme: {
    color: white;
    background-color: red;
  }
}

.danger {
  @apply --danger-theme;
}
```
