### ISSUE TITLE
Custom properties in IE11

### ISSUE THREAD

**Issue by axyz** [csstools/postcss-preset-env#201]
Hi, maybe I'm doing something wrong while migrating from cssnext to preset-env, but passing the browserslist option and explicitly including IE11 should apply the postcss-custom-properties plugin and substitute them with their actual values as they are not supported in IE11.

sample css:
```css
:root {
  my-var: 1em;
}

.my-class {
  font-size: var(--my-var);
}
```

sample config:
```js
postcss([
  postcssPresetEnv({
    browsers: ["> 1%", "IE 11"],
    autoprefixer: { cascade: false },
  })
])
```

result (wrong):
```css
:root {
  my-var: 1em;
}

.my-class {
  font-size: var(--my-var);
}
```

result (expected):
```css
.my-class {
  font-size: 1em;
}
```

codepen to reproduce: https://codesandbox.io/s/sweet-chandrasekhar-bsb8q?file=/src/index.js:169-278  
(check on console)

Thanks for your time.
