### ISSUE TITLE
linear-gradient causes infinite loop

### ISSUE THREAD

**Issue by mischnic** [csstools/postcss-preset-env#233]
Input code:
```css
.progress-bar-striped {
  background-image: linear-gradient(
    45deg,
    rgba(255, 255, 255, 0.15) 25%,
    transparent 25%,
    transparent 50%,
    rgba(255, 255, 255, 0.15) 50%,
    rgba(255, 255, 255, 0.15) 75%,
    transparent 75%,
    transparent
  );
}
```

.postcssrc.json
```
{
	"plugins": {
		"postcss-preset-env": true
	}
}
```

Running `postcss input.css` (using https://www.npmjs.com/package/postcss-cli) runs into an infinite loop and at some point the process crashes with OOM.
