### ISSUE TITLE
Local custom properties won't work

### ISSUE THREAD

**Issue by gijsroge** [csstools/postcss-preset-env#34]
It seems like only custom properties defined in :root are being polyfilled.

Reproducible codepen: https://codepen.io/gijs/pen/KepYJz (set percentage to > 2%)

Output:
```css 
html {
  --padding: 4em;
  padding: 0 var(--padding);
  padding: 0 var(--padding);
}
```

Expected output would be:
```css 
html {
  --padding: 4em;
  padding: 0 4em;
  padding: 0 var(--padding);
}
```
