### ISSUE TITLE
Not removed :root scope

### ISSUE THREAD

**Issue by sibicode** [csstools/postcss-preset-env#49]
Custom properties have been removed, but **:root** scope empty and is not removed, if in **:root** has comments

My postcss.config.js
```js
plugins: [
    require('postcss-import'),
    require('postcss-preset-env')({
      stage: 0,
      features: {
        'custom-properties': {
          preserve: false
        }
      }
    }),
    require('autoprefixer')
  ]
```

index.css
```css
@import '/variables.css';
@import '/foo.css';
@import '/bar.css';
```

variables.css
```css

:root {
  /*------------------------------------------------------------------
   LINKS
  ------------------------------------------------------------------
  */
--link-color: var(--blue-light);
}
```

output 
```css
:root {
  /*------------------------------------------------------------------
   LINKS
  ------------------------------------------------------------------
  */
}

*,
*::before,
*::after {
  box-sizing: border-box;
}

html {
  font-family: sans-serif;
  line-height: 1.15;
  -webkit-text-size-adjust: 100%;
  -ms-text-size-adjust: 100%;
  -ms-overflow-style: scrollbar;
  -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
}
....
```
