### ISSUE TITLE
Custom Properties not passing preserve

### ISSUE THREAD

**Issue by alisonailea** [csstools/postcss-preset-env#54]
## Input
second.css
```css
:root {
  --color: red;
}
```

base.css
```css
@import './second.css';

.test {
  color: var(--color);
}
```

webpack.config.js
```js
{
        test: /\.css$/,
        use: [
          MiniCssExtractPlugin.loader,
          {
            loader: 'css-loader',
            options: { importLoaders: 1 }
          }, {
            loader: 'postcss-loader',
            options: {
              config: {
                ctx: {
                  presetEnv: {
                    stage: 0,
                    features: {
                      'custom-properties': {
                        preserve: true,
                      },
                      'custom-media-queries': {
                        preserve: true,
                        extensions: require('./src/tokens/medias').css
                      }
                    }
                  },
                  cssnano: { /* only runs in production */
                    preset: ['default', {}]
                  },
                }
              }
            }
          }
        ],
      },
```

---
## Expected Output

bundle.css
```css
:root {
  --color: red;
}
.test {
  color: red;
  color: var(--color);
}
```

---
## Current Output
bundle.css
```
:root {
  --color: red;
}
.test {
  color: var(--color);
  color: var(--color);
}
```

Can someone tell me what I'm doing wrong? Or is there a bug?

**Comment by pascalduez** [comment]
Missing `postcss-import` plugin?

**Comment by jonathantneal** [comment]
@alisonailea, did @pascalduez’s idea to use `postcss-import` resolve your issue?

**Comment by padupuy** [comment]
Hi @alisonailea @pascalduez @jonathantneal , i made an example project to reproduce the issue https://github.com/padupuy/parcel-playground

There is also an other problem, the `@custom-media` is deleted ...
Is this a problem of configuration ?

**Comment by padupuy** [comment]
@pascalduez thanks for the quick reply, I just try to invert the plugin orders and the result is the same.

This is my output : 
```css
/*---variables---*/
:root {
  --font: Tahoma, Verdana, Segoe, sans-serif;

  --gutter: 2rem;

  --primary: #0e5d6d;
  --secondary: #da9383;
}
/*---variables---*/
/*---custom---*/
/*---custom---*/
body {
  background-color: var(--secondary);
  background-color: var(--secondary);
  color: var(--primary);
  color: var(--primary);
  font-family: var(--font);
  font-family: var(--font);
}

```
