### ISSUE TITLE
postcss-custom-properties error

### ISSUE THREAD

**Issue by zyy7259** [csstools/postcss-preset-env#69]
input

```postcss
:root {
  --color: red;
}

h1 {
  --padding: 10px;

  padding: var(--padding);
  color: var(--color);
}
```

output

```css
:root {
  --color: red;
}
h1 {
  --padding: 10px;

  padding: var(--padding);

  padding: var(--padding);
  color: red;
  color: var(--color);
}
```

postcss.config.js

```js
  const browsers = [
    'last 2 versions',
    'Firefox ESR',
    '> 1%',
    'iOS >= 8',
    'Android >= 4',
  ]
  if (pc) {
    browsers.push('ie >= 8')
  }

  const postcssConfig = {
    // do not set `map` here
    // https://github.com/postcss/postcss-loader/issues/207#issuecomment-301255032
    // https://github.com/michael-ciniawsky/postcss-load-config#plugins
    plugins: {
      'postcss-partial-import': {
        path: [process.cwd()],
      },
      precss: {
        // postcss-preset-env options
        browsers,
      },
      'postcss-pxtorem': rem ? pxtorem : false,
      'postcss-inline-svg': {
        path: process.cwd(),
      },
      autoprefixer: {
        browsers,
      },
    },
  }
```

Anything wrong?
