### ISSUE TITLE
Warning when using a feature not covered by the stage

### ISSUE THREAD

**Issue by moonglum** [csstools/postcss-preset-env#80]
First of all: This is a great project – thank you so much for it 🙇 

I have a question regarding features that are not covered by your stage range. Let's say that we have the following code:

```css
body {
  font-family: system-ui;
}
```

If I compile this with stage 2 and target `IE 11`, I will get the following result:

```css
body {
  font-family: system-ui, -apple-system, Segoe UI, Roboto, Ubuntu, Cantarell, Noto Sans, sans-serif;
}
```

This is a stage 2 feature. When I say that I only support stage 3, then I get the following result:

```css
body {
  font-family: system-ui;
}
```

I would expect to receive an error (or at least a warning) in that case, because I'm using a feature from a stage that I don't support. What is your reasoning behind this? Or can I maybe configure this to raise an error/warning?
