### ISSUE TITLE
Custom selectors breaking

### ISSUE THREAD

**Issue by iamso** [csstools/postcss-preset-env#89]
Hi

after reading that cssNext has been deprecated and that I should use postcss-preset-env instead, I have done just that. At least I have updated my project template to use the new plugin.

I have then tested it on a personal project I had been working on and it broke my css. Mainly it broke my custom selectors. After trying to find the error, I've found that it works in very few cases, but doesn't in most.

Here is some sample code:
```postcss
@custom-selector :--nav-open-header .site-loaded .nav-toggle-input:checked ~ .site-header &;
@custom-selector :--nav-open-header-no-touch .site-loaded.no-touchevents .nav-toggle-input:checked ~ .site-header &;

/* first one works, second one breaks */
:--nav-open-header ul,
:--nav-open-header-no-touch:hover ul {
  background: red;
}

/* both break */
ul {
  :--nav-open-header,
  :--nav-open-header-no-touch:hover {
    background: red;
  }  
}

/* this one breaks too */
ul {
  &,
  :--nav-open-header {
    background: red;
  }
}

/* this one doesn't break */
ul {
  :--nav-open-header,
  & {
    background: red;
  }
}

/* here the second one breaks again */
ul {
  :--nav-open-header,
  :--nav-open-header-no-touch:hover,
  & {
    background: red;
  }
}
```

I have tested this code here https://preset-env.cssdb.org/playground and it behaves exactly as in my local setup.

Don't worry about the nesting, I use another postcss plugin to take care of that. But most of that code would break with or without nesting. I have tested that too.

Please let me know, if I can do anything more to help.

Thanks
Steve

**Comment by jonathantneal** [comment]
It looks like you were using some invalid queries. You may have been using an older version of cssnext that did not respect the web standard.

```
ul {
  :--nav-open-header
```

That is not possible.

**Comment by iamso** [comment]
@jonathantneal this is totally irrelevant. As mentioned before, the nesting is handled by another postcss plugin.

To illustrate, go ahead to https://preset-env.cssdb.org/playground and try the following code (with no nesting this time 😉):
```postcss
@custom-selector :--nav-open-header .site-loaded .nav-toggle-input:checked ~ .site-header;
@custom-selector :--nav-open-header-no-touch .site-loaded.no-touchevents .nav-toggle-input:checked ~ .site-header;

:--nav-open-header ul,
:--nav-open-header-no-touch:hover ul {
  background: red;
}
```

The expected output is this:
```css
.site-loaded .nav-toggle-input:checked~.site-header ul,
.site-loaded .no-touchevents .nav-toggle-input:checked~.site-header:hover ul {
  background: red;
}
```

But what you get instead is this:
```css
.site-loaded .nav-toggle-input:checked~.site-header ul,
.site-loaded
.no-touchevents 
.nav-toggle-input
:checked
~
.site-header:hover ul {
  background: red;
}
```

As you can see, it breaks the `:checked` part of the selector and therefore it doesn't work.

It does work if you only use one, but with two, like in this example, it breaks the second one.
