### ISSUE TITLE
Supports for @nest

### ISSUE THREAD

**Issue by jonathandion** [csstools/postcss-preset-env#96]
Any supports for `@nest` rule?

**Comment by jonathantneal** [comment]
Yes, please refer to the documentation.  You’d need to set the `stage` option to `0` to use it. https://github.com/csstools/postcss-preset-env#stage

CSS Nesting is a Stage 0 feature. https://cssdb.org/#nesting-rules

**Comment by jonathandion** [comment]
@jonathantneal 

I'm facing issues with:

```css
@define-mixin hide-this-on-IE11 {
  @nest _:-ms-input-placeholder, :root & {
    display: none;
  }
}

.u-hide\@ie {
  @mixin hide-this-on-IE11;
}
```

Thanks.
