### ISSUE TITLE
@nest not compiled with :root, :-ms-input-placeholder

### ISSUE THREAD

**Issue by jonathandion** [csstools/postcss-preset-env#97]
I'm facing issues with:

```css
@define-mixin hide-this-on-IE11 {
  @nest _:-ms-input-placeholder, :root & {
    display: none;
  }
}

@define-mixin rules-for-IE11 {
  @nest _:-ms-input-placeholder, :root & {
    @mixin-content;
  }
};

.u-hide\@ie {
  @mixin hide-this-on-IE11;
}
```

The ouput shows `@nest`
